# Generated by Django 6.0.3 on 2026-05-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
